# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\PycharmProjects\Vahtan\UI\EnterPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnterPasswordWin(object):
    def setupUi(self, EnterPasswordWin):
        EnterPasswordWin.setObjectName("EnterPasswordWin")
        EnterPasswordWin.resize(365, 248)
        EnterPasswordWin.setStyleSheet("*{\n"
"font-family:Century Gothic;\n"
"}\n"
"QPushButton\n"
"{\n"
"background:rgba(0, 131, 96, 140);\n"
"color:white;\n"
"border-radius: 8px;\n"
"}\n"
"QLabel\n"
"{\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:rgba(85, 85, 85,30);\n"
"border:none;\n"
"border-bottom: 1px solid rgb(149, 149, 149);\n"
"border-left: 1px solid rgb(149, 149, 149);\n"
"color: rgb(149, 149, 149);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background:rgba(85, 170, 127, 140);\n"
"border-radius: 8px;\n"
"color:white;\n"
"}\n"
"QFrame\n"
"{\n"
"background:url(:/newPrefix/fone.jpg)\n"
"}")
        self.frame = QtWidgets.QFrame(EnterPasswordWin)
        self.frame.setGeometry(QtCore.QRect(-440, -50, 1151, 1011))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(490, 164, 269, 20))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(490, 104, 269, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(490, 200, 269, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(EnterPasswordWin)
        QtCore.QMetaObject.connectSlotsByName(EnterPasswordWin)

    def retranslateUi(self, EnterPasswordWin):
        _translate = QtCore.QCoreApplication.translate
        EnterPasswordWin.setWindowTitle(_translate("EnterPasswordWin", "Form"))
        self.label.setText(_translate("EnterPasswordWin", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Введите пароль:</span></p></body></html>"))
        self.pushButton.setText(_translate("EnterPasswordWin", "Подтвердить"))
import qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnterPasswordWin = QtWidgets.QWidget()
    ui = Ui_EnterPasswordWin()
    ui.setupUi(EnterPasswordWin)
    EnterPasswordWin.show()
    sys.exit(app.exec_())
