# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\PycharmProjects\Vahtan\UI\MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 594)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/ICON.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"font-family:Century Gothic;\n"
"}\n"
"QPushButton\n"
"{\n"
"background:rgba(0, 131, 96, 140);\n"
"color:white;\n"
"border-radius: 8px;\n"
"}\n"
"QMainWindow\n"
"{\n"
"background:url(:/newPrefix/fone.jpg);\n"
"}\n"
"QListWidget\n"
"{\n"
"background:rgba(145, 145, 145, 30);\n"
"border:none;\n"
"border-bottom: 1px solid rgb(149, 149, 149);\n"
"border-left: 1px solid rgb(149, 149, 149);\n"
"}\n"
"QListWidget:item\n"
"{\n"
"color:white;\n"
"}\n"
"QLabel\n"
"{\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"#OutEncryptBtt\n"
"{\n"
"font: 75 15pt \"Century Gothic\";\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:rgba(85, 85, 85,30);\n"
"border:none;\n"
"border-bottom: 1px solid rgb(149, 149, 149);\n"
"border-left: 1px solid rgb(149, 149, 149);\n"
"color: rgb(149, 149, 149);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:rgba(85, 170, 127, 140);\n"
"border-radius: 8px;\n"
"color:white;\n"
"}\n"
"#pushButton\n"
"{\n"
"background:rgba(0, 175, 0, 140);\n"
"border-radius: 6px;\n"
"color:white;\n"
"}\n"
"#pushButton:hover\n"
"{\n"
"background:rgba(255, 255, 0, 140);\n"
"border-radius: 6px;\n"
"color:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 271, 371))
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 10, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.EncryptDirLineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.EncryptDirLineedit.setGeometry(QtCore.QRect(290, 80, 291, 21))
        self.EncryptDirLineedit.setInputMask("")
        self.EncryptDirLineedit.setText("")
        self.EncryptDirLineedit.setObjectName("EncryptDirLineedit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 50, 281, 20))
        self.label_7.setObjectName("label_7")
        self.ViewDirsBtt = QtWidgets.QPushButton(self.centralwidget)
        self.ViewDirsBtt.setGeometry(QtCore.QRect(590, 75, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.ViewDirsBtt.setFont(font)
        self.ViewDirsBtt.setIconSize(QtCore.QSize(30, 30))
        self.ViewDirsBtt.setObjectName("ViewDirsBtt")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(290, 104, 241, 31))
        self.label_11.setObjectName("label_11")
        self.PasswordlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordlineEdit.setGeometry(QtCore.QRect(290, 134, 231, 20))
        self.PasswordlineEdit.setText("")
        self.PasswordlineEdit.setObjectName("PasswordlineEdit")
        self.EncryptDirBtt = QtWidgets.QPushButton(self.centralwidget)
        self.EncryptDirBtt.setGeometry(QtCore.QRect(530, 130, 101, 28))
        self.EncryptDirBtt.setObjectName("EncryptDirBtt")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 180, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ViewDirsBtt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ViewDirsBtt_2.setGeometry(QtCore.QRect(590, 241, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.ViewDirsBtt_2.setFont(font)
        self.ViewDirsBtt_2.setIconSize(QtCore.QSize(30, 30))
        self.ViewDirsBtt_2.setObjectName("ViewDirsBtt_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(290, 216, 281, 20))
        self.label_9.setObjectName("label_9")
        self.PasswordlineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordlineEdit_2.setGeometry(QtCore.QRect(290, 300, 231, 20))
        self.PasswordlineEdit_2.setText("")
        self.PasswordlineEdit_2.setObjectName("PasswordlineEdit_2")
        self.OpenDirLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OpenDirLineEdit.setGeometry(QtCore.QRect(290, 246, 291, 21))
        self.OpenDirLineEdit.setText("")
        self.OpenDirLineEdit.setObjectName("OpenDirLineEdit")
        self.AddBtt = QtWidgets.QPushButton(self.centralwidget)
        self.AddBtt.setGeometry(QtCore.QRect(530, 296, 101, 28))
        self.AddBtt.setObjectName("AddBtt")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(290, 270, 231, 31))
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 500, 271, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 420, 231, 51))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 480, 251, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 340, 341, 19))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 370, 161, 16))
        self.label_3.setObjectName("label_3")
        self.OldPasswordLineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.OldPasswordLineedit.setGeometry(QtCore.QRect(290, 390, 291, 22))
        self.OldPasswordLineedit.setObjectName("OldPasswordLineedit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 430, 171, 16))
        self.label_4.setObjectName("label_4")
        self.NewPasswordLineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.NewPasswordLineedit.setGeometry(QtCore.QRect(290, 450, 231, 22))
        self.NewPasswordLineedit.setObjectName("NewPasswordLineedit")
        self.ChangePasswordBtt = QtWidgets.QPushButton(self.centralwidget)
        self.ChangePasswordBtt.setGeometry(QtCore.QRect(530, 447, 101, 28))
        self.ChangePasswordBtt.setObjectName("ChangePasswordBtt")
        self.label_6.raise_()
        self.listWidget.raise_()
        self.label_2.raise_()
        self.EncryptDirLineedit.raise_()
        self.label_7.raise_()
        self.ViewDirsBtt.raise_()
        self.label_11.raise_()
        self.PasswordlineEdit.raise_()
        self.EncryptDirBtt.raise_()
        self.label_8.raise_()
        self.ViewDirsBtt_2.raise_()
        self.label_9.raise_()
        self.PasswordlineEdit_2.raise_()
        self.OpenDirLineEdit.raise_()
        self.AddBtt.raise_()
        self.label_12.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.label_10.raise_()
        self.label_3.raise_()
        self.OldPasswordLineedit.raise_()
        self.label_4.raise_()
        self.NewPasswordLineedit.raise_()
        self.ChangePasswordBtt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vahta N"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Открыть зашифрованный файл</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Зашифровать файлы </span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Укажите путь к файлу:</p></body></html>"))
        self.ViewDirsBtt.setText(_translate("MainWindow", "Обзор"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Укажите пароль для дешифровки:</p></body></html>"))
        self.EncryptDirBtt.setText(_translate("MainWindow", "Зашифровать"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Добавить уже зашифрованные файлы</span></p></body></html>"))
        self.ViewDirsBtt_2.setText(_translate("MainWindow", "Обзор"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Укажите путь к файлу:</p></body></html>"))
        self.AddBtt.setText(_translate("MainWindow", "Добавить"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Укажите пароль для дешифровки:</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "$ Поддержать разработчика $"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Не заудте зашифровать файлы </p><p align=\"center\">снова!</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Зашифровать"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Изменить пароль</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Введите старый пароль:"))
        self.label_4.setText(_translate("MainWindow", "Введите новый пароль:"))
        self.ChangePasswordBtt.setText(_translate("MainWindow", "Изменить"))
import qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
